// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xonuxqfhgbufwkjeddfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvbnV4cWZoZ2J1ZndramVkZGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzY5MjAsImV4cCI6MjA2NDAxMjkyMH0.j9Hmy-x9QAOb-8etbrjd9WIu8AYxVcZ-T26AH25v5r8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);